[app]
name = "Tigrissystem Security"


[discord]
intents = ["GUILDS", "GUILD_MEMBERS", "GUILD_MESSAGES", "MESSAGE_CONTENT", "GUILD_MESSAGE_REACTIONS", "GUILD_VOICE_STATES"]


[database]
statement_timeout_ms = 5000


[logging]
json = false

[chatguard]
racial_slurs = [
  '(?i)\bnazi\b',
  '(?i)\bhitler\b',
  '(?i)\bheil\b',
  '(?i)\bkkk\b',
  '(?i)\bwhite\s*power\b',
  '(?i)\bczarn\w+\b',
]

[antinuke]
threshold = 5
redis_url = "redis://localhost/0"
s3_bucket = ""