[app]
name = "Tigrissystem Security"


[discord]
intents = ["GUILDS", "GUILD_MEMBERS", "GUILD_MESSAGES", "MESSAGE_CONTENT", "GUILD_MESSAGE_REACTIONS"]


[database]
statement_timeout_ms = 5000


[logging]
json = true

[chatguard]
racial_slurs = [
  '(?i)\bnazi\b',
  '(?i)\bhitler\b',
  '(?i)\bheil\b',
  '(?i)\bkkk\b',
  '(?i)\bwhite\s*power\b',
  '(?i)\bczarn\w+\b',
]